### ISSUE TITLE
Support listening on a UNIX socket

### ISSUE THREAD

**Issue by ip1981** [zalora/sproxy-web#11]
Support listening on a UNIX socket for security reasons.

**Comment by shlevy** [comment]
Can you outline a specific use case?

**Comment by ip1981** [comment]
"Trust no one" policy.
Every local user can do `curl http://localhost:8080`

**Comment by ip1981** [comment]
[Sproxy](https://github.com/zalora/sproxy) supports backends at a UNIX socket since 0.9.3.

**Comment by ip1981** [comment]
https://github.com/zalora/sproxy-web/commit/877113527d4d52e0eeca456dd6fa2c783087d3bd
