### ISSUE TITLE
Using citext for email field seems to break sproxy-web

### ISSUE THREAD

**Issue by lenguyenthedat** [zalora/sproxy-web#7]
Sproxy commit: https://github.com/zalora/sproxy/commit/3bc7a61acd8e4f3a12fa7e726e8d1c3f5595c7c4

After applied:

![screen shot 2014-11-18 at 18 21 15](https://cloud.githubusercontent.com/assets/1543321/5085742/b4fe2d2a-6f4f-11e4-9b60-1c01a24db933.png)

@sol  @soenkehahn

**Comment by ip1981** [comment]
https://github.com/lpsmith/postgresql-simple/commit/bcbacfe9f2184692c5426ab9f6b89a2c4c4752b0
